### ISSUE TITLE
[minor] Build failure with ./configure --enable-static=yes --enable-shared=no

### ISSUE THREAD

**Issue by rustyrussell** [jgriffiths/libwally-core#16]
$ make distclean
$ ./tools/autogen.sh && ./configure --enable-static=yes --enable-shared=no && make
...
libtool: link: ( cd ".libs" && rm -f "libwallycore.la" && ln -s "../libwallycore.la" "libwallycore.la" )
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I../include -pthread -O3 -D_FORTIFY_SOURCE=1 -fstack-protector-strong -DNDEBUG=1 -flto -flax-vector-conversions -Wall -Wextra -Wpedantic -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wno-unused-function -Wno-long-long -Wno-overlength-strings -Wformat -Wformat-security -Wformat-nonliteral -fvisibility=hidden   -O3 -flto -Wl,-z,relro -o test_clear ctest/test_clear-test_clear.o libwallycore.la 
libtool: link: gcc -I../include -pthread -O3 -D_FORTIFY_SOURCE=1 -fstack-protector-strong -DNDEBUG=1 -flto -flax-vector-conversions -Wall -Wextra -Wpedantic -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wno-unused-function -Wno-long-long -Wno-overlength-strings -Wformat -Wformat-security -Wformat-nonliteral -fvisibility=hidden -O3 -flto -Wl,-z -Wl,relro -o test_clear ctest/test_clear-test_clear.o  ./.libs/libwallycore.a -pthread
/tmp/ccDZ9SHD.ltrans2.ltrans.o: In function `wally_internal_ec_nonce_fn.lto_priv.9':
<artificial>:(.text+0x2): undefined reference to `secp256k1_nonce_function_default'
collect2: error: ld returned 1 exit status
Makefile:862: recipe for target 'test_clear' failed
make[3]: *** [test_clear] Error 1
make[3]: Leaving directory '/home/rusty/devel/cvs/libwally-core/src'
Makefile:1095: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/rusty/devel/cvs/libwally-core/src'
Makefile:687: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/rusty/devel/cvs/libwally-core/src'
Makefile:426: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Also, using --enable-tests=no doesn't seem to suppress this (which seems to be a test?).

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety

$ gcc --version
gcc (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.27
Copyright (C) 2016 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

$ git describe
release_0.2.0-15-g7d3768a

**Comment by jgriffiths** [comment]
Hmm, the problem is that in static builds we need to link secp in addition to wally. I'll try to find the automake incantation that can work around this.

Note that ./tools/cleanup.sh is preferred before making bug reports, since autotools aren't very good at really cleaning up after themselves (or at least, not when I'm driving 'em).

**Comment by jgriffiths** [comment]
@rustyrussell Can you confirm this fixes things for you?

**Comment by jgriffiths** [comment]
> Also, using --enable-tests=no doesn't seem to suppress this (which seems to be a test?).

Wally doesn't support --enable-tests=no :-)

**Comment by jgriffiths** [comment]
@rustyrussell please re-open if this isn't fixed for you now.
