### ISSUE TITLE
Add new test vectors for BIP32

### ISSUE THREAD

**Issue by greenaddress** [jgriffiths/libwally-core#17]
Some BIP32 libraries have been affected by a (deterministic) bug that causes wrong derivation.

New vectors have been proposed to avoid more libraries hitting the issue.

We should add these vectors to the tests src/test/test_bip32.py 

vectors: https://github.com/bitcoin/bips/pull/497

**Comment by jgriffiths** [comment]
See commit 0b1dadc3ff37014015145b8d71c6277231d335fd - wally is not affected by this bug.
